server:
  port: 8090
spring:
  main:
    web-application-type: reactive
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: AUTH-SERVICE
          uri: http://localhost:8091
          predicates:
           - Path=/auth-service/**
          filters:
            - StripPrefix=1
        - id: REST-SERVICE
          uri: http://localhost:8092
          predicates:
            - Path=/rest-service/**
          filters:
            - StripPrefix=1